# Generated by Django 5.1.1 on 2024-11-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lang',
            new_name='lat',
        ),
    ]
